// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Veterinaria.Infrastructure;

namespace Veterinaria.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221216053039_Models")]
    partial class Models
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Veterinaria.Models.DataModels.Cita", b =>
                {
                    b.Property<int>("IdCita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdDueno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdVeterinario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VeterinarioIdVeterinario")
                        .HasColumnType("int");

                    b.HasKey("IdCita");

                    b.HasIndex("VeterinarioIdVeterinario");

                    b.ToTable("Cita");
                });

            modelBuilder.Entity("Veterinaria.Models.DataModels.Dueno", b =>
                {
                    b.Property<int>("IdDueno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Cedula")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDueno");

                    b.ToTable("Dueno");
                });

            modelBuilder.Entity("Veterinaria.Models.DataModels.Historial", b =>
                {
                    b.Property<int>("IdHistorial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Diagnostico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdVeterinario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotivoConsulta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VeterinarioIdVeterinario")
                        .HasColumnType("int");

                    b.HasKey("IdHistorial");

                    b.HasIndex("VeterinarioIdVeterinario");

                    b.ToTable("Historial");
                });

            modelBuilder.Entity("Veterinaria.Models.DataModels.Mascota", b =>
                {
                    b.Property<int>("IdMascota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DuenoIdDueno")
                        .HasColumnType("int");

                    b.Property<int>("IdDueno")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Raza")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("IdMascota");

                    b.HasIndex("DuenoIdDueno");

                    b.ToTable("Mascota");
                });

            modelBuilder.Entity("Veterinaria.Models.DataModels.Veterinario", b =>
                {
                    b.Property<int>("IdVeterinario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Cedula")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdVeterinario");

                    b.ToTable("Veterinarios");
                });

            modelBuilder.Entity("Veterinaria.Models.DataModels.Cita", b =>
                {
                    b.HasOne("Veterinaria.Models.DataModels.Veterinario", "Veterinario")
                        .WithMany()
                        .HasForeignKey("VeterinarioIdVeterinario");

                    b.Navigation("Veterinario");
                });

            modelBuilder.Entity("Veterinaria.Models.DataModels.Historial", b =>
                {
                    b.HasOne("Veterinaria.Models.DataModels.Veterinario", "Veterinario")
                        .WithMany()
                        .HasForeignKey("VeterinarioIdVeterinario");

                    b.Navigation("Veterinario");
                });

            modelBuilder.Entity("Veterinaria.Models.DataModels.Mascota", b =>
                {
                    b.HasOne("Veterinaria.Models.DataModels.Dueno", "Dueno")
                        .WithMany()
                        .HasForeignKey("DuenoIdDueno");

                    b.Navigation("Dueno");
                });
#pragma warning restore 612, 618
        }
    }
}
